### ISSUE TITLE
`~~NOFOOTER~~`Doesn't work if it's the first line of the page.

### ISSUE THREAD

**Issue by ryliejamesthomas** [Juergen-aus-Zuendorf/dokuwiki-plugin-footer#1]
Hi, just noticed the behaviour mentioned in the issue title, that the `~~NOFOOTER~~` line doesn't seem to have an effect (footer appears and `~~NOFOOTER~~` text remains) if it's the first line in the file. Works as expected if I place it's anywhere else.

**Comment by Juergen-aus-Zuendorf** [comment]
I added a file "syntax.php" to the newest release which should solve the problem. Please update the plugin, then this new file should be included in the plugin folder "footer".
 This is probably related to the cache problem, where I am still looking for a solution

**Comment by ryliejamesthomas** [comment]
Thanks, I'll get it a try by early next week.

**Comment by ryliejamesthomas** [comment]
Updating the plugin completely broke my wiki (would only render a blank page) and I had to go back to the old one.

**Comment by Juergen-aus-Zuendorf** [comment]
Oh, sorry! I made a small correction, now it should work so far.

**Comment by ryliejamesthomas** [comment]
I've updated, and it still doesn't work if the nofooter is on line 1.

For comparison's sake, using the notoc command on line 1 works fine.

It's not a pressing issue btw; easy enough to work around :)
